export const user = (email, first_name, last_name, password) => ({
  email,
  first_name,
  last_name,
  password,
  username: email,
  billing: {
    first_name: "",
    last_name: "",
    company: "",
    address_1: "",
    address_2: "",
    city: " ",
    state: "",
    postcode: "",
    country: "",
    email,
    phone: "",
  },
  shipping: {
    first_name: "",
    last_name: "",
    company: "",
    address_1: "",
    address_2: "",
    city: "",
    state: "",
    postcode: "",
    country: "",
  },
});
