import Layout from "components/Layout";
import Navbar from "components/Navbar";
import Footer from "components/Footer";
import styles from "./policy.module.scss";

const TnC = () => {
  return (
    <Layout title="Privacy Policy" description={null} keywords={null}>
      <div className={styles.container}>
        <Navbar />
        <section>
          <h1>Terms and Conditions</h1>
        </section>
        <section>
          <p>
            Welcome to mytryshop.com (the "website") which provide access to you
            subject to the conditions set forth herein. Please read these
            conditions carefully before using the website. By using website, you
            signify your agreement to be bound by these conditions. These "Terms
            and Conditions" constitute an electronic record within the meaning
            of the applicable law. This electronic record is generated by a
            computer system and does not require any physical or digital
            signatures.
          </p>
        </section>
        <section>
          <h2>Your Account</h2>
          <p>
            Upon use of the website, you are solely responsible for maintaining
            the confidentiality of your account and password and for restricting
            access to your computer to prevent unauthorised access to your
            account. You agree to accept responsibility for all activities that
            occur under your account or password. You should take all necessary
            steps to ensure that the password is kept confidential and secure
            and should inform us immediately if you have any reason to believe
            that your password has become known to anyone else, or if the
            password is being, or is likely to be, used in an unauthorised
            manner.
          </p>
          <p>
            Please ensure that the details you provide upon registration are
            correct. Inform us immediately in writing of any changes to the
            information that you provided when registering. You can access and
            update much of the information you provided us. Website reserves the
            right to refuse access to the website, terminate accounts, remove or
            edit content at any time without notice to you.
          </p>
        </section>
        <section>
          <h2>Privacy</h2>
          <p>
            Privacy Policy governs your visit to mytryshop.com. The personal
            information / data provided to us by you during the course of usage
            of website will be treated as strictly confidential and in
            accordance with the Privacy Policy and applicable laws and
            regulations. If you object to your information being transferred or
            used, please do not use the website.
          </p>
        </section>
        <section>
          <h2>Access to website</h2>
          <p>
            We will do our best ensure hassle-free website access without any
            interruption but cannot be guaranteed. Also, your access to the
            website may also be occasionally suspended or restricted to allow
            for repairs, maintenance, or the introduction of new facilities or
            services at any time without prior notice.
          </p>
        </section>
        <section>
          <h2>Copyright, authors' rights and database rights</h2>
          <p>
            All content included on the website, such as text, images, graphics,
            logos, button icons, audio clips, video clips are property of
            mytryshop.com is protectable under applicable Indian Law, common law
            or international copyright, laws. The compilation of all content on
            this website is the exclusive property of mytryshop.com.
          </p>
        </section>
        <section>
          <h2>Trademarks</h2>
          <p>
            MYTRY BY MAITRI indicated on our website are trademarks or
            registered trademarks of MAITRI DOSHI.
          </p>
        </section>
        <section>
          <h2>Disclaimer</h2>
          <p>
            You acknowledge and undertake that you are accessing the services on
            the website and transacting at your own risk and are using your best
            and prudent judgment before entering into any transactions through
            the website.
          </p>
        </section>
        <section>
          <h2>Indemnification</h2>
          <p>
            You shall indemnify and hold harmless MyTry, its subsidiaries,
            affiliates and their respective officers, directors, agents and
            employees, from any claim or demand, or actions including reasonable
            attorney's fees, made by any third party or penalty imposed due to
            or arising out of your breach of these Conditions of Use or any
            document incorporated by reference, or your violation of any law,
            rules, regulations or the rights of a third party.
          </p>
        </section>
        <section>
          <h2>Children</h2>
          <p>
            Use of website is available only to persons who can form a legally
            binding contract under the Indian Contract Act, 1872. If you are a
            minor i.e. under the age of 18 years, you may use with the
            involvement of adult supervision.
          </p>
        </section>
        <section>
          <h2>Losses</h2>
          <p>
            We will not be responsible for any business loss (including loss of
            profits, revenue, contracts, anticipated savings, data, goodwill or
            wasted expenditure) or any other indirect or consequential loss that
            is not reasonably foreseeable to both you and us when you commenced
            using the website.
          </p>
        </section>
        <section>
          <h2>Alteration of Service or Amendments to the Conditions</h2>
          <p>
            We reserve the right to make changes to our website, policies, and
            these Conditions of Use at any time. If any of these conditions is
            deemed invalid, void, or for any reason unenforceable, that
            condition will be deemed severable and will not affect the validity
            and enforceability of any remaining condition. Entire part of this
            conditions cannot be consider invalid.
          </p>
        </section>
        <section>
          <h2>Governing law and Jurisdiction</h2>
          <p>
            These conditions are governed by and construed in accordance with
            the laws of India and the exclusive jurisdiction of the courts at
            Surat.
          </p>
        </section>
        <Footer />
      </div>
    </Layout>
  );
};

export default TnC;
