export const FETCH_CART = "FETCH_CART";
export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const INCREASE_ITEM_QTY = "INCREASE_ITEM_QTY";
export const DECREASE_ITEM_QTY = "DECREASE_ITEM_QTY";

export const SET_CATEGORY = "SET_CATEGORY"
export const UNSET_CATEGORY = "UNSET_CATEGORY"
